[listener]
protocol = 20
submit_contract_address = ""
submit_buffer = 2
off_chain_trigger_delay_seconds = 15
relay_contract_address = ""
relay_buffer = 2
fdc_contract_address = ""
request_buffer = 5
request_interval_seconds = 2


[logger]
file = ""
prefix = ""
flag = 0
