[indexer]
start_index = 16123418        # the number of the block that the indexer will start with
stop_index = 0                # the number of the block that the indexer will stop with; set 0 or skip to index indefinitely
num_parallel_req = 100        # the number of threads doing requests to the chain in parallel
batch_size = 1000             # the number of blocks that will be pushed to a database in a batch (should be divisible by num_parallel_req)
log_range = 10                # the size of the interval of blocks used to request logs in each request; suggested value is log_range = batch_size / num_parallel_req; note that a blockchain node might have an upper bound on this
new_block_check_millis = 1000 # interval for checking for new blocks

[[indexer.collect_transactions]]
contract_address = "0x2cA6571Daa15ce734Bbd0Bf27D5C9D16787fc33f" # Submission
func_sig = "6c532fae"
status = true
collect_events = true

[[indexer.collect_transactions]]
contract_address = "0x2cA6571Daa15ce734Bbd0Bf27D5C9D16787fc33f" # Submission
func_sig = "9d00c9fd"
status = true
collect_events = true

[[indexer.collect_transactions]]
contract_address = "0x2cA6571Daa15ce734Bbd0Bf27D5C9D16787fc33f" # Submission
func_sig = "57eed580"
status = true
collect_events = true

[[indexer.collect_transactions]]
contract_address = "0x32D46A1260BB2D8C9d5Ab1C9bBd7FF7D7CfaabCC" # Relay
func_sig = "b59589d1"
status = true
collect_events = true


[[indexer.collect_logs]]
contract_address = "0x85680Dd93755Fe5d0789773fd0896cEE51F9e358" # FlareSystemsManager
topic = "undefined"

[[indexer.collect_logs]]
contract_address = "0x051E9Cb16A8676C011faa10efA1ABE95372e7825" # VoterRegistry
topic = "undefined"

[[indexer.collect_logs]]
contract_address = "0x43CBAB9C953F54533aadAf7ffCD13c30ec05Edc9" # FlareSystemsCalculator
topic = "undefined"

[[indexer.collect_logs]]
contract_address = "0x32D46A1260BB2D8C9d5Ab1C9bBd7FF7D7CfaabCC" # Relay
topic = "undefined"

[[indexer.collect_logs]]
contract_address = "0xC9534cB913150aD3e98D792857689B55e2404212" # FtsoRewardOffersManager
topic = "undefined"


[[indexer.collect_logs]]
contract_address = "0xCf6798810Bc8C0B803121405Fee2A5a9cc0CA5E5" # FdcHub
topic = "undefined"


[db]
host = "indexer-db"
port = 3306
database = "flare_ftso_indexer"
username = "root"
password = "root"
log_queries = false
drop_table_at_start = false
history_drop = 3628800          # 42 days

[logger]
level = "INFO"
file = "/tmp/flare-ftso-indexer.log"
console = true
