services:
  indexer-db:
    container_name: ${COMPOSE_PROJECT_NAME}-indexer-db
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    # volumes:
    #   - ./c-chain-init.sql:/docker-entrypoint-initdb.d/db_init.sql
    #   - indexer_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent", "--host", "localhost", "-proot"]
      timeout: 20s
      retries: 10
    ports:
      - "3308:3306"

  indexer:
    container_name: ${COMPOSE_PROJECT_NAME}-indexer
    image: ghcr.io/flare-foundation/flare-system-c-chain-indexer:latest
    volumes:
      - ./c-chain-index-config.toml:/app/config.toml
    restart: unless-stopped
    depends_on:
      indexer-db:
        condition: service_healthy

# volumes:
#   indexer_data:
