[listener]
protocol = 200
submit_contract_address = "0x2cA6571Daa15ce734Bbd0Bf27D5C9D16787fc33f"
submit_buffer = 2
off_chain_trigger_delay_seconds = 15
relay_contract_address = "0x32D46A1260BB2D8C9d5Ab1C9bBd7FF7D7CfaabCC"
relay_buffer = 2
fdc_contract_address = "0xCf6798810Bc8C0B803121405Fee2A5a9cc0CA5E5"
request_buffer = 5
request_interval_seconds = 2


[logger]
file = ""
prefix = ""
flag = 0

[rest_server]
title = "FDC protocol data provider API"
fsp_sub_router_title = "FDC protocol data provider for FSP client"
fsp_sub_router_path = "/fsp"
version = "0.0.0"
swagger_path = "/api-doc"