
# options are: "coston", "songbird", "coston2", "flare"
chain = "coston"

protocolId = 200

[db]
host = "localhost"
port = 3306
database = "flare_ftso_indexer"
username = "root"
password = "root"
log_queries = false

[rest_server]
# Addr optionally specifies the TCP address for the server to listen on, in the form "host:port". If empty, ":http" (port 80) is used. The service names are defined in RFC 6335 and assigned by IANA. See net.Dial for details of the address format.
addr = ":8080"
api_key_name = "X-API-KEY"
api_keys = ["12345", "123456"]
title = "FDC protocol data provider API"
fsp_sub_router_title = "FDC protocol data provider for FSP client"
fsp_sub_router_path = "/fsp"
version = "0.0.0"
swagger_path = "/api-doc"


[logger]
file = ""
prefix = ""
flag = 0


# # Payment
# [types.Payment]
# abi_path = ""

# ## BTC
# [types.Payment.Sources.BTC]
# url = ""
# api_key = "12345"
# lut_limit = "18446744073709551615"

# ## DOGE
# [types.Payment.Sources.DOGE]
# url = ""
# api_key = ""
# lut_limit = "18446744073709551615"

# ## XRP
# [types.Payment.Sources.XRP]
# url = ""
# api_key = ""
# lut_limit = "18446744073709551615"


# EVMTransaction
[types.EVMTransaction]
abi_path = "configs/abis/EVMTransaction.json"

## ETH
[types.EVMTransaction.Sources.ETH]
url = "http://localhost:4500/eth/EVMTransaction/verifyFDC"
api_key = "12345"
lut_limit = "18446744073709551615"
queue = "evmETH"

##SGB
[types.EVMTransaction.Sources.testSGB]
url = "http://localhost:4500/eth/EVMTransaction/verifyFDC"
api_key = "12345"
lut_limit = "18446744073709551615"
queue = "evmETH"


##FLR
[types.EVMTransaction.Sources.testFLR]
url = "http://localhost:4500/eth/EVMTransaction/verifyFDC"
api_key = "12345"
lut_limit = "18446744073709551615"
queue = "evmETH"


[queues.evmETH]
size = 10
max_dequeues_per_second = 0
max_workers = 0
max_attempts = 3
