[db]
host = "localhost"
port = 3306
database = "flare_ftso_indexer"
username = "root"
password = "root"
log_queries = false

[rest_server]
# Addr optionally specifies the TCP address for the server to listen on, in the form "host:port". If empty, ":http" (port 80) is used. The service names are defined in RFC 6335 and assigned by IANA. See net.Dial for details of the address format.
addr = ":8080"
api_key_name = "X-API-KEY"
api_keys = ["12345", "123456"]


# # Verifiers for BTC
# [verifiers.BTC.Payment]
# url = "url"
# api_key = "key"
# lut_limit = 0


# [verifiers.BTC.BalanceDecreasingTransaction]
# url = "url"
# api_key = "key"
# lut_limit = 0


# [verifiers.BTC.ConfirmedBlockHeightExists]
# url = "url"
# api_key = "key"
# lut_limit = 0


# [verifiers.BTC.ReferencedPaymentNonexistence]
# url = "url"
# api_key = "key"
# lut_limit = 0


# [verifiers.BTC.AddressValidity]
# url = "url"
# api_key = "key"
# lut_limit = 0


# # Verifiers for DOGE
# [verifiers.DOGE.Payment]
# url = "url"
# api_key = "key"
# lut_limit = 0


# [verifiers.DOGE.BalanceDecreasingTransaction]
# url = "url"
# api_key = "key"
# lut_limit = 0


# [verifiers.DOGE.ConfirmedBlockHeightExists]
# url = "url"
# api_key = "key"
# lut_limit = 0


# [verifiers.DOGE.ReferencedPaymentNonexistence]
# url = "url"
# api_key = "key"
# lut_limit = 0


# [verifiers.DOGE.AddressValidity]
# url = "url"
# api_key = "key"
# lut_limit = 0


# # Verifiers for XRP
# [verifiers.XRP.Payment]
# url = "url"
# api_key = "key"
# lut_limit = 0


# [verifiers.XRP.BalanceDecreasingTransaction]
# url = "url"
# api_key = "key"
# lut_limit = 0


# [verifiers.XRP.ConfirmedBlockHeightExists]
# url = "url"
# api_key = "key"
# lut_limit = 0


# [verifiers.XRP.ReferencedPaymentNonexistence]
# url = "url"
# api_key = "key"
# lut_limit = 0


# [verifiers.XRP.AddressValidity]
# url = "url"
# api_key = "key"
# lut_limit = 0


# Verifiers for ETH
[verifiers.ETH.EVMTransaction]
url = "http://localhost:4500/eth/EVMTransaction/verifyFDC"
api_key = "12345"
lut_limit = "18446744073709551615"


[verifiers.testSGB.EVMTransaction]
url = "http://localhost:4500/eth/EVMTransaction/verifyFDC"
api_key = "12345"
lut_limit = "18446744073709551615"


[verifiers.testFLR.EVMTransaction]
url = "http://localhost:4500/eth/EVMTransaction/verifyFDC"
api_key = "12345"
lut_limit = "18446744073709551615"


#ABIs
[abis]
# Payment = ""
# BalanceDecreasingTransaction = ""
# ConfirmedBlockHeightExists = ""
# ReferencedPaymentNonexistence = ""
# AddressValidity = ""
EVMTransaction = "configs/abis/EVMTransaction.json" #relative to project root
